### PR TITLE
Support windows

### PR DESCRIPTION
**Pull request by dy**
This fixes https://github.com/substack/node-shell-quote/issues/30 and makes tests pass in windows.
Also makes possible to run [glslify](https://github.com/glslify/) tests in windows.

@karissa @jiwaddell @substack please have a look.

### CODE REVIEW

**Comment by karissa** [comment]
Looks good, it'd be great to have travis and appveyor set up

**Comment by dy** [comment]
@karissa done https://travis-ci.org/dy/node-shell-quote

**Comment by karissa** [comment]
@substack what do you think?

**Comment by dy** [comment]
@substack ping

**Comment by goto-bus-stop** [comment]
:package: 1.6.3

**Comment by goto-bus-stop** [comment]
the path unescaping here introduced a regression. i'm reverting it for now.

**Pull request merged**
