### PR TITLE
Use native JSON and Array methods

### PR DESCRIPTION
**Pull request by zertosh**

### CODE REVIEW

**Comment by alexeyraspopov** [comment]
@substack, do you mind merging this? Having zero dependencies is a big win.

**Comment by srghma** [comment]
Since this RP is from `unknown repository` (arrg)
I was able to remove the dependency on jsonify doing

1. make a clone
2. `git fetch upstream pull/21/head:without_unlicenced_jsonify`
3. push without_unlicenced_jsonify branch
4. in package.json

```
  "resolutions": {
    "json-stable-stringify": "git+https://github.com/ForbesLindesay/stable-stringify.git#master",
    "shell-quote": "git+https://github.com/srghma/node-shell-quote.git#without_unlicenced_jsonify"
  },

```

**Comment by karissa** [comment]
Or you could use something like license zero

**Comment by goto-bus-stop** [comment]
:package: 1.6.2
thanks!

**Pull request merged**
